import { CHARACTER_TAGS, MARKET_TAGS } from "@/lib/content/rice";
import type { CollectionKey } from "@/lib/content/types";

/**
 * Declarative admin schema. Each collection's editor form, list view and server-side
 * whitelist are generated from these definitions — adding a field here is enough to
 * make it editable.
 */
export type FieldDef =
  | { name: string; label: string; type: "text" | "textarea" | "url" | "number" | "boolean" | "slug" | "list" | "icon" | "date"; help?: string; required?: boolean; rows?: number; placeholder?: string }
  | { name: string; label: string; type: "select"; options: { value: string; label: string }[]; help?: string; required?: boolean }
  | { name: string; label: string; type: "media"; accept: "image" | "video" | "document" | "any"; help?: string; required?: boolean }
  | { name: string; label: string; type: "pairs" | "images" | "videos" | "stats" | "highlights" | "expressions"; help?: string; required?: boolean }
  | { name: string; label: string; type: "tags"; options: readonly string[]; help?: string; required?: boolean };

export interface CollectionConfig {
  key: CollectionKey;
  slug: string;
  label: string;
  singular: string;
  description: string;
  titleField: string;
  subtitleField?: string;
  thumbField?: string;
  fields: FieldDef[];
}

const opts = (...values: string[]) => values.map((v) => ({ value: v, label: v.replace(/-/g, " ").replace(/^\w/, (c) => c.toUpperCase()) }));
const mediaType = { name: "mediaType", label: "Media type", type: "select" as const, options: opts("image", "video") };
const provider = { name: "provider", label: "Video source", type: "select" as const, options: [{ value: "mp4", label: "MP4 / self-hosted" }, { value: "youtube", label: "YouTube" }, { value: "vimeo", label: "Vimeo" }] };

export const COLLECTIONS: CollectionConfig[] = [
  {
    key: "products",
    slug: "products",
    label: "Products",
    singular: "Product",
    description: "Rice products shown in the catalogue, each with its own detail page.",
    titleField: "name",
    subtitleField: "variety",
    fields: [
      { name: "name", label: "Product name", type: "text", required: true },
      { name: "slug", label: "URL slug", type: "slug", help: "Used in the product page URL. Generated from the name if left empty." },
      { name: "variety", label: "Rice variety", type: "text" },
      { name: "category", label: "Category", type: "text", placeholder: "e.g. Basmati, Non-Basmati, Parboiled" },
      { name: "shortDescription", label: "Short description", type: "textarea", rows: 2 },
      { name: "overview", label: "Product overview", type: "textarea", rows: 6 },
      { name: "images", label: "Product images", type: "images", help: "First image is used on product cards. WebP/AVIF/JPEG recommended, at least 1600px." },
      { name: "videos", label: "Product videos", type: "videos" },
      { name: "grainLength", label: "Grain length", type: "text" },
      { name: "texture", label: "Texture", type: "text" },
      { name: "appearance", label: "Appearance", type: "text" },
      { name: "expressions", label: "Processing expressions", type: "expressions", help: "Raw, Steam, Creamy Sella, Golden Sella… each with its own verified specification. Lengths like '8.30–8.35 mm' drive the grain-length ruler." },
      { name: "cookedLength", label: "Typical cooked length", type: "text", placeholder: "e.g. 20–22 mm", help: "Shown as elongation on the grain-length ruler." },
      { name: "characterTags", label: "Grain & cooking character", type: "tags", options: CHARACTER_TAGS, help: "Used by the 'Explore by character' filter." },
      { name: "marketTags", label: "Market & programme fit", type: "tags", options: MARKET_TAGS },
      { name: "specifications", label: "Additional specifications", type: "pairs", help: "e.g. Purity — 95% min. Only enter verified values." },
      { name: "qualityInfo", label: "Quality information", type: "textarea", rows: 4 },
      { name: "packagingOptions", label: "Packaging options", type: "list", help: "One per line." },
      { name: "availableQuantities", label: "Available quantities", type: "text" },
      { name: "exportAvailability", label: "Export availability", type: "textarea", rows: 2 },
      { name: "applications", label: "Applications", type: "list", help: "One per line." },
      { name: "grainTone", label: "Artwork tone (used until photos are uploaded)", type: "select", options: opts("white", "cream", "golden", "brown", "husk") },
      { name: "featured", label: "Feature on home page", type: "boolean" },
      { name: "sampleData", label: "Sample data (untick once every value is verified)", type: "boolean", help: "Sample products show a badge and are hidden from visitors when placeholder mode is off." },
    ],
  },
  {
    key: "processingSteps",
    slug: "processing",
    label: "Processing Steps",
    singular: "Processing step",
    description: "The Paddy-to-Premium-Rice story.",
    titleField: "title",
    subtitleField: "number",
    thumbField: "mediaUrl",
    fields: [
      { name: "number", label: "Step number", type: "text", placeholder: "01" },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "summary", label: "Summary", type: "text" },
      { name: "description", label: "Description", type: "textarea", rows: 4 },
      { name: "icon", label: "Icon", type: "icon" },
      { name: "mediaUrl", label: "Image / video", type: "media", accept: "any" },
      mediaType,
    ],
  },
  {
    key: "technologies",
    slug: "technology",
    label: "Technology",
    singular: "Technology item",
    description: "Processing technology cards. Only describe equipment and capabilities you actually operate.",
    titleField: "title",
    thumbField: "mediaUrl",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", rows: 4 },
      { name: "icon", label: "Icon", type: "icon" },
      { name: "mediaUrl", label: "Image / video", type: "media", accept: "any" },
      mediaType,
    ],
  },
  {
    key: "qualityChecks",
    slug: "quality-checks",
    label: "Quality Checks",
    singular: "Quality check",
    description: "Checks listed in the Quality Control section.",
    titleField: "title",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", rows: 3 },
      { name: "icon", label: "Icon", type: "icon" },
    ],
  },
  {
    key: "certifications",
    slug: "certifications",
    label: "Certifications",
    singular: "Certification",
    description: "Only add certificates and standards the company actually holds.",
    titleField: "name",
    subtitleField: "issuer",
    thumbField: "imageUrl",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "kind", label: "Type", type: "select", options: [{ value: "certification", label: "Certification" }, { value: "standard", label: "Quality standard" }] },
      { name: "issuer", label: "Issuing body", type: "text" },
      { name: "certificateNumber", label: "Certificate number", type: "text" },
      { name: "validUntil", label: "Valid until", type: "date" },
      { name: "imageUrl", label: "Certificate image", type: "media", accept: "image" },
      { name: "documentUrl", label: "Certificate PDF", type: "media", accept: "document" },
    ],
  },
  {
    key: "trustItems",
    slug: "trust",
    label: "Trust & Credibility",
    singular: "Trust item",
    description: "Registrations, export documentation, buyer logos, awards, memberships and associations. Verified information only.",
    titleField: "title",
    subtitleField: "kind",
    thumbField: "imageUrl",
    fields: [
      { name: "kind", label: "Type", type: "select", options: opts("registration", "export-document", "buyer-logo", "award", "membership", "association") },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", rows: 2 },
      { name: "imageUrl", label: "Logo / image", type: "media", accept: "image" },
      { name: "url", label: "Link (optional)", type: "url" },
    ],
  },
  {
    key: "exportCountries",
    slug: "export-countries",
    label: "Export Countries",
    singular: "Export country",
    description: "Destinations shown on the globe. Use coordinates of the destination port or city.",
    titleField: "name",
    subtitleField: "region",
    fields: [
      { name: "name", label: "Country", type: "text", required: true },
      { name: "region", label: "Region", type: "text" },
      { name: "port", label: "Destination port", type: "text" },
      { name: "lat", label: "Latitude", type: "number", help: "e.g. 25.27 for Dubai" },
      { name: "lng", label: "Longitude", type: "number", help: "e.g. 55.29 for Dubai" },
      { name: "isMajorMarket", label: "Major market", type: "boolean" },
      { name: "note", label: "Note", type: "text" },
      { name: "isPlaceholder", label: "Sample entry (untick once this is a real destination)", type: "boolean" },
    ],
  },
  {
    key: "exportRoutes",
    slug: "export-routes",
    label: "Export Routes",
    singular: "Export route",
    description: "Optional port-to-port shipping lanes, drawn on the globe in addition to export countries.",
    titleField: "name",
    subtitleField: "destinationPort",
    fields: [
      { name: "name", label: "Route name", type: "text", required: true },
      { name: "originPort", label: "Origin port", type: "text" },
      { name: "originLat", label: "Origin latitude", type: "number" },
      { name: "originLng", label: "Origin longitude", type: "number" },
      { name: "destinationPort", label: "Destination port", type: "text" },
      { name: "destinationLat", label: "Destination latitude", type: "number" },
      { name: "destinationLng", label: "Destination longitude", type: "number" },
      { name: "mode", label: "Mode", type: "select", options: opts("sea", "air", "land") },
      { name: "transitNote", label: "Transit note", type: "text" },
    ],
  },
  {
    key: "exportSteps",
    slug: "export-process",
    label: "Export Process",
    singular: "Export step",
    description: "The inquiry-to-delivery workflow for international buyers.",
    titleField: "title",
    subtitleField: "number",
    fields: [
      { name: "number", label: "Step number", type: "text" },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", rows: 3 },
      { name: "icon", label: "Icon", type: "icon" },
    ],
  },
  {
    key: "factoryMedia",
    slug: "factory-media",
    label: "Factory Media",
    singular: "Factory image / video",
    description: "Infrastructure gallery: mill, plant, machinery, storage, laboratory, loading.",
    titleField: "title",
    subtitleField: "category",
    thumbField: "url",
    fields: [
      { name: "title", label: "Title", type: "text" },
      { name: "description", label: "Description", type: "textarea", rows: 2 },
      { name: "category", label: "Category", type: "select", options: opts("rice-mill", "processing-plant", "machinery", "storage", "warehouse", "packaging", "laboratory", "loading", "container") },
      { name: "type", label: "Type", type: "select", options: opts("image", "video") },
      { name: "url", label: "File or video URL", type: "media", accept: "any", required: true, help: "Upload an image/MP4, or paste a YouTube/Vimeo link." },
      provider,
      { name: "posterUrl", label: "Video poster image", type: "media", accept: "image" },
    ],
  },
  {
    key: "videos",
    slug: "videos",
    label: "Videos",
    singular: "Video",
    description: "Cinematic video section. Videos only load when a visitor presses play.",
    titleField: "title",
    subtitleField: "category",
    thumbField: "posterUrl",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Short description", type: "textarea", rows: 2 },
      { name: "category", label: "Category", type: "text", placeholder: "e.g. Factory walkthrough" },
      provider,
      { name: "url", label: "Video URL / file", type: "media", accept: "video", required: true },
      { name: "posterUrl", label: "Thumbnail", type: "media", accept: "image", help: "Optional for YouTube (thumbnail is fetched automatically)." },
      { name: "duration", label: "Duration", type: "text", placeholder: "2:45" },
      { name: "featured", label: "Featured (large card)", type: "boolean" },
    ],
  },
  {
    key: "kitchenVideos",
    slug: "kitchen",
    label: "Kitchen Videos",
    singular: "Kitchen video",
    description: "Vertical (9:16) recipe and serving reels shown in Kitchen Creativity. Upload a light MP4 (about 540×960) for the cards and optionally an HD version for full screen.",
    titleField: "title",
    subtitleField: "tag",
    thumbField: "posterUrl",
    fields: [
      { name: "title", label: "Dish name", type: "text", required: true },
      { name: "tag", label: "Tag", type: "text", placeholder: "e.g. Biryani, Fried Rice, Pulao" },
      { name: "description", label: "Short caption", type: "textarea", rows: 2 },
      { name: "videoUrl", label: "Card video (MP4, vertical)", type: "media", accept: "video", required: true },
      { name: "videoHdUrl", label: "HD video for full screen (optional)", type: "media", accept: "video" },
      { name: "posterUrl", label: "Poster image", type: "media", accept: "image" },
    ],
  },
  {
    key: "packaging",
    slug: "packaging",
    label: "Packaging",
    singular: "Packaging option",
    description: "Packaging formats. Leave specifications empty until confirmed.",
    titleField: "name",
    subtitleField: "packType",
    thumbField: "imageUrl",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "packType", label: "Mockup style", type: "select", options: opts("consumer", "bulk", "export", "custom") },
      { name: "description", label: "Description", type: "textarea", rows: 2 },
      { name: "sizes", label: "Packaging size(s)", type: "text" },
      { name: "material", label: "Material", type: "text" },
      { name: "privateLabel", label: "Private label availability", type: "text" },
      { name: "moq", label: "Minimum order quantity", type: "text" },
      { name: "imageUrl", label: "Product photo (replaces mockup)", type: "media", accept: "image" },
    ],
  },
  {
    key: "testimonials",
    slug: "testimonials",
    label: "Testimonials",
    singular: "Testimonial",
    description: "Real buyer testimonials only, published with the customer's permission. The section is hidden when empty.",
    titleField: "customerName",
    subtitleField: "company",
    thumbField: "imageUrl",
    fields: [
      { name: "customerName", label: "Customer name", type: "text", required: true },
      { name: "company", label: "Company", type: "text" },
      { name: "country", label: "Country", type: "text" },
      { name: "imageUrl", label: "Profile image", type: "media", accept: "image" },
      { name: "quote", label: "Testimonial", type: "textarea", rows: 4, required: true },
    ],
  },
  {
    key: "partnerReasons",
    slug: "why-us",
    label: "Why Partner With Us",
    singular: "Reason",
    description: "Hidden on the live site while descriptions are still [placeholders].",
    titleField: "title",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea", rows: 3 },
      { name: "icon", label: "Icon", type: "icon" },
    ],
  },
  {
    key: "socialLinks",
    slug: "social",
    label: "Social Links",
    singular: "Social link",
    description: "Shown in the footer and in Organization structured data.",
    titleField: "platform",
    subtitleField: "url",
    fields: [
      { name: "platform", label: "Platform", type: "select", options: opts("linkedin", "instagram", "facebook", "youtube", "x", "whatsapp") },
      { name: "url", label: "Profile URL", type: "url", required: true },
    ],
  },
];

export const BASE_FIELDS: FieldDef[] = [
  { name: "published", label: "Published", type: "boolean" },
  { name: "sortOrder", label: "Sort order", type: "number" },
];

export const COMPANY_FIELDS: FieldDef[] = [
  { name: "name", label: "Company name", type: "text", required: true },
  { name: "legalName", label: "Registered / legal name", type: "text" },
  { name: "tagline", label: "Tagline", type: "text" },
  { name: "shortDescription", label: "Short description", type: "textarea", rows: 2 },
  { name: "story", label: "Company story", type: "textarea", rows: 8, help: "Separate paragraphs with a blank line." },
  { name: "foundedYear", label: "Year established", type: "text" },
  { name: "logoUrl", label: "Logo — light version (for dark backgrounds)", type: "media", accept: "image", help: "Transparent PNG/WebP, white or light colour. Used on the hero, footer and dark sections." },
  { name: "logoDarkUrl", label: "Logo — dark version (for light backgrounds)", type: "media", accept: "image", help: "Transparent PNG/WebP in a dark colour. Used on the cream navigation bar after scrolling." },
  { name: "heroHeadline", label: "Hero headline", type: "text", help: "Sentences separated by '. ' become separate lines." },
  { name: "heroSubheadline", label: "Hero sub-headline", type: "textarea", rows: 2 },
  { name: "heroVideoUrl", label: "Hero fallback video (MP4)", type: "media", accept: "video", help: "Shown on devices that cannot run the 3D scene." },
  { name: "heroPosterUrl", label: "Hero poster image", type: "media", accept: "image" },
  { name: "aboutMediaUrl", label: "About section image / video", type: "media", accept: "any" },
  { name: "aboutMediaType", label: "About media type", type: "select", options: opts("image", "video") },
  { name: "stats", label: "Statistics", type: "stats", help: "Only enter verified figures. Empty values show as placeholders (or are hidden when placeholders are off)." },
  { name: "highlights", label: "About highlights", type: "highlights" },
  { name: "address", label: "Address", type: "textarea", rows: 3 },
  { name: "phone", label: "Phone", type: "text" },
  { name: "email", label: "Email", type: "text" },
  { name: "whatsapp", label: "WhatsApp number (with country code)", type: "text", placeholder: "+91 98765 43210" },
  { name: "businessHours", label: "Business hours", type: "text" },
  { name: "mapEmbedUrl", label: "Google Maps embed URL", type: "url", help: "Google Maps → Share → Embed a map → copy the src URL." },
  { name: "mapLink", label: "Google Maps link", type: "url" },
  { name: "originLabel", label: "Origin label on the globe", type: "text" },
  { name: "originCountry", label: "Origin country", type: "text" },
  { name: "originPort", label: "Origin port", type: "text" },
  { name: "originLat", label: "Origin latitude", type: "number" },
  { name: "originLng", label: "Origin longitude", type: "number" },
];

export const SETTINGS_FIELDS: FieldDef[] = [
  { name: "showPlaceholders", label: "Show placeholder slots", type: "boolean", help: "Turn OFF before launch: empty sections and [bracketed] placeholder text are then hidden from visitors." },
  { name: "seoTitle", label: "Default SEO title", type: "text" },
  { name: "seoDescription", label: "Default meta description", type: "textarea", rows: 3 },
  { name: "seoKeywords", label: "Keywords", type: "list", help: "One per line. Only keywords that match your actual products." },
  { name: "ogImageUrl", label: "Social share image (1200×630)", type: "media", accept: "image" },
  { name: "twitterHandle", label: "X / Twitter handle", type: "text", placeholder: "@company" },
  { name: "exportHeadline", label: "Export headline", type: "text" },
  { name: "exportIntro", label: "Export introduction", type: "textarea", rows: 3 },
  { name: "shippingCapability", label: "Shipping capability", type: "textarea", rows: 3 },
  { name: "internationalSupply", label: "International supply", type: "textarea", rows: 3 },
  { name: "majorMarketsNote", label: "Major markets note", type: "textarea", rows: 2 },
  { name: "qualityIntro", label: "Quality section introduction", type: "textarea", rows: 2 },
  { name: "privacyPolicy", label: "Privacy policy", type: "textarea", rows: 12 },
  { name: "terms", label: "Terms of use", type: "textarea", rows: 12 },
  { name: "imageAbout", label: "Page header photo — About", type: "media", accept: "image" },
  { name: "imageProducts", label: "Page header photo — Products", type: "media", accept: "image" },
  { name: "imagePackaging", label: "Page header photo — Packaging", type: "media", accept: "image" },
  { name: "imageProcessing", label: "Page header photo — Processing", type: "media", accept: "image" },
  { name: "imageQuality", label: "Page header photo — Quality", type: "media", accept: "image" },
  { name: "imageExport", label: "Page header photo — Global Export", type: "media", accept: "image" },
  { name: "imageInfrastructure", label: "Page header photo — Infrastructure", type: "media", accept: "image" },
  { name: "imageVideos", label: "Page header photo — Videos", type: "media", accept: "image" },
  { name: "imageContact", label: "Page header photo — Contact", type: "media", accept: "image" },
  { name: "imageQuote", label: "Page header photo — Request a Quote", type: "media", accept: "image" },
];

export const collectionBySlug = (slug: string) => COLLECTIONS.find((c) => c.slug === slug);
